# Generated by Django 4.1.2 on 2022-12-14 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AdminApp", "0004_paymentmaster"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=7)),
                ("dateOfOrder", models.DateTimeField(default=datetime.datetime.now)),
                ("details", models.CharField(max_length=300)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdminApp.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "OrderMaster",
            },
        ),
    ]
